name       : python-astor
version    : 0.8.1
release    : 6
source     :
    - https://github.com/berkerpeksag/astor/archive/0.8.1.tar.gz : eee1edbf7d58dbc01f0e42fa1a6a1e15470335ec6b82f090dfcf18c10d27c89c
license    : BSD-3-Clause
component  : programming.python
summary    : Python AST read/write
description: |
    Astor is designed to allow easy manipulation of Python source via the AST.
build      : |
    %python3_setup
install    : |
    %python3_install
