name       : python-astor
version    : 0.8.0
release    : 2
source     :
    - https://github.com/berkerpeksag/astor/archive/0.8.tar.gz : e1161080b18ac49498e9a2fe6d4914072b06312fa4d373c980f61a907d86a00e
license    : BSD-3-Clause
component  : programming.python
summary    : Python AST read/write
description: |
    Astor is designed to allow easy manipulation of Python source via the AST.
build      : |
    %python3_setup
install    : |
    %python3_install
